modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/XircTwerk/Meal-Mastery/issues"

[[mods]]
modId = "mealmastery"
version = "${version}"
displayName = "Farmer's Delight: Meal Mastery"
displayTest = "MATCH_VERSION"
authors = "xirc"
displayURL = "https://github.com/XircTwerk/Meal-Mastery"
logoFile = "assets/mealmastery/icon.png"
description = '''
Turns every meal you cook in Farmer's Delight into persistent culinary progression: mastery, discovery, journals, statistics and challenges.
'''

[[dependencies.mealmastery]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mealmastery]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mealmastery]]
modId = "farmersdelight"
mandatory = true
versionRange = "${farmersdelight_forge_version_range}"
ordering = "AFTER"
side = "BOTH"
